title: Zala
buildFuture: true
defaultContentLanguage: en
languageCode: es
baseURL: https://status.zala.app
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Landing
      category: Reservas
    - name: Checkout
      category: Reservas
    - category: Panel
      name: Turnos
    - name: Disponibilidad
      category: Panel
    - name: Historia Clinica
      category: Panel
    - name: Integraciones
      category: Panel
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#480090"
  enableLastMod: true
  headerTextColor: white
  logo: /img/logo-zala.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Reservas
    - name: Panel
    - name: API
  description: Monitoreamos continuamente el estado de nuestros servicios y, si
    hay alguna interrupción, se publicará una nota acá.
  enableCustomHTML: true
  useLargeHeaderDesign: false
